spring:
  application:
    name: wandoor

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/WANDOOR_DB"
    username: ${DB_USERNAME:wandoor}
    password: ${DB_PASSWORD:root}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

  flyway:
    enabled: false
    default-schema: WANDOOR
    schemas: WANDOOR
    create-schemas: false
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.wandoor@gmail.com
    password: nzsn zqay hwok fozq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    transport:
      protocol: smtp
    default-encoding: UTF-8

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:rediswandoor}

logging:
  level:
    root: INFO
    com.wandoor: INFO
    org.springframework.security: INFO
    org.springframework.data.redis.core.RedisTemplate: INFO
    io.lettuce.core.protocol: INFO
    org.springframework.web: DEBUG
    org.apache.catalina: DEBUG
    org.springdoc: DEBUG
    io.swagger: DEBUG

# secret & expiry JWT
app:
  jwt:
    secret: ${JWT_SECRET:MySuperSecretKeyForBankingApp}
    expiration-ms: 3600000

server:
  port: 8081
  address: 0.0.0.0
  forward-headers-strategy: native
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/springboot
      prefix: access_log
      suffix: .log
      pattern: "%h %l %u %t \"%r\" %s %b"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics,loggers"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    show-details: always

springdoc:
  api-docs:
    path: /api/v1/openapi
  swagger-ui:
    path: /api/v1/swagger-ui.html
    disable-swagger-default-url: true
    url: /api/v1/openapi
    
  packages-to-scan: com.example.wandoor.controller
  paths-to-match: /api/auth/**, /api/v1/**, /api/admin/**
  remove-broken-reference-definitions: true
