BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MANAGEMENT DROP CONSTRAINT FK_ROLE_MGMT_PROFILE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN -- ORA-02443: constraint not found
            RAISE;
        END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MANAGEMENT DROP COLUMN USER_ID';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 THEN -- ORA-00904: column not found
            RAISE;
        END IF;
END;
/
