DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRX_HISTORY' AND COLUMN_NAME = 'CATEGORY_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRX_HISTORY ADD CATEGORY_ID VARCHAR2(21)';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_TRX_HISTORY_CATEGORY_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TRX_HISTORY_CATEGORY_ID ON TRX_HISTORY (CATEGORY_ID)';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'FK_TRX_HISTORY_CATEGORY' AND TABLE_NAME = 'TRX_HISTORY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRX_HISTORY ADD CONSTRAINT FK_TRX_HISTORY_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES TRX_CATEGORY (ID)';
    END IF;
END;
/