name: CI Wandoor App

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: password
        options: >-
          --health-cmd="echo 'select 1 from dual;' | sqlplus -s system/password@localhost:1521/XEPDB1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Wait for Oracle DB to be ready
        run: |
          echo "Waiting for Oracle DB to start..."
          for i in {1..30}; do
            nc -z localhost 1521 && echo "Oracle is ready!" && break
            echo "Still waiting..."
            sleep 10
          done

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            jrtr1/wandoor-backend-app:backend-${{ github.sha }}
            jrtr1/wandoor-backend-app:backend-latest

      # === Update tag di repo infra ===
      - name: Checkout infra repository (staging branch)
        uses: actions/checkout@v3
        with:
          repository: kelompok-3-odp343/infra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: infra
          ref: staging

      - name: Update image tag in backend deployment
        run: |
          cd infra/k3s/backend-wandoor
          sed -i "s|jrtr1/wandoor-backend-app:.*|jrtr1/wandoor-backend-app:backend-${{ github.sha }}|g" backend-deployment.yaml

      - name: Commit and push updated image tag to staging branch
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Tambahkan perintah untuk memastikan tidak error jika tidak ada perubahan
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update backend image tag to backend-${{ github.sha }}"
            git push origin staging
          fi

      # === Update tag di repo infra ===
      - name: Checkout infra repository (production branch)
        uses: actions/checkout@v3
        with:
          repository: kelompok-3-odp343/infra
          token: ${{ secrets.ACCESS_TOKEN }}
          path: infra
          ref: production

      - name: Update image tag in backend deployment
        run: |
          cd infra/k3s-manifests/backend-wandoor
          sed -i "s|jrtr1/wandoor-backend-app:.*|jrtr1/wandoor-backend-app:backend-${{ github.sha }}|g" backend-deployment.yaml

      - name: Commit and push updated image tag to production branch
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Tambahkan perintah untuk memastikan tidak error jika tidak ada perubahan
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update backend image tag to backend-${{ github.sha }}"
            git push origin production
          fi
